export const SAVE_USER = 'SAVE_USER';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
//export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
//export const SET_LOGIN_ERROR = 'SET_LOGIN_ERROR';
//export const SET_REGISTRATION_ERROR = 'SET_REGISTRATION_ERROR';
